import { CardData } from "./src/constants"

export const OC_CARD_DATA: CardData[] = [
  {
    uploader: "现充爆炸乐队",
    clubname: "现充爆炸乐队",
    clubiconPath: "",
    category: "[OC]",
    typeIndex: "",
    title: "【永夜原创曲】夏枯蝉雨 【现充爆炸乐队】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2025-10-06",
    bvid: "BV1csHGz3E7C",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1csHGz3E7C.mp4",
  },
  {
    uploader: "西安高校vocaloid创作社",
    clubname: "西安高校vocaloid创作社",
    clubiconPath: "",
    category: "[OC]",
    typeIndex: "",
    title: "【洛天依/乐正绫原创】岁暮歌【西安高校Vocaloid联合创作会】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2026-02-16",
    bvid: "BV1hYcgzeEFH",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1hYcgzeEFH.mp4",
  },
  {
    uploader: "我只笑笑不说话鸭",
    clubname: "我只笑笑不说话鸭",
    clubiconPath: "",
    category: "[OC]",
    typeIndex: "",
    title: "【徵羽摩柯七周年】请为我画一只绵羊【LV7：循风轻旅】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2025-12-10",
    bvid: "BV1mtmJBQE7X",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1mtmJBQE7X.mp4",
  },
  {
    uploader: "洛天依P",
    clubname: "洛天依P",
    clubiconPath: "",
    category: "[OC]",
    typeIndex: "",
    title: "2026年了，还有人愿意听这样的民国风原创歌曲吗？【洛天依、乐正绫】乡·水·忆｜“乡水一如初见”【南北组】【“梦光之约”新春歌会单品】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2026-02-20",
    bvid: "BV1S5fgBfEZY",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1S5fgBfEZY.mp4",
  },
]



export const RT_CARD_DATA: CardData[] = [
  {
    uploader: "竹川ホタル",
    clubname: "竹川ホタル",
    clubiconPath: "",
    category: "[RT]",
    typeIndex: "",
    title: "【音街ウナ＆重音テト】カワユイ星【Synthesizer V cover】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2026-02-20",
    bvid: "BV1Wgf3BHEH2",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1Wgf3BHEH2.mp4",
  },
  {
    uploader: "星韵社",
    clubname: "星韵社",
    clubiconPath: "",
    category: "[RT]",
    typeIndex: "",
    title: "【飞梦ACE COVER】404 NOT FOUND【飞梦ACG联萌秋季百团应援曲】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2025-10-11",
    bvid: "BV1yc4AzYENZ",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1yc4AzYENZ.mp4",
  },
]



export const VC_IC_CARD_DATA: CardData[] = [
  {
    uploader: "DarkBlue深蓝动漫社",
    clubname: "DarkBlue深蓝动漫社",
    clubiconPath: "",
    category: "[VC]",
    typeIndex: "",
    title: "【深蓝动漫节】神的随波逐流｜深蓝动漫社",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2025-12-16",
    bvid: "BV12gqaBxEks",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV12gqaBxEks.mp4",
  },
  {
    uploader: "银精灵_",
    clubname: "银精灵_",
    clubiconPath: "",
    category: "[VC]",
    typeIndex: "",
    title: "我们二次元有自己的难忘今宵",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2026-02-16",
    bvid: "BV1WMZABoEbM",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1WMZABoEbM.mp4",
  },
  {
    uploader: "鲁东澪幻空间动漫社",
    clubname: "鲁东澪幻空间动漫社",
    clubiconPath: "",
    category: "[VC]",
    typeIndex: "",
    title: "【澪幻空间】宅歌配音部合唱第一期《勾指起誓》",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2025-11-13",
    bvid: "BV1Z8CtBmE6a",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1Z8CtBmE6a.mp4",
  },
]

export const SP_CardData: CardData[] = [
  {
    uploader: "南时薰official",
    clubname: "南时薰official",
    clubiconPath: "",
    category: "[OC]",
    typeIndex: "",
    title: "【南时薰原创】薰风来时【午时华岁~2026三校联合拜年祭单品】",
    vocal: "",
    vocalColor: "",
    musicStaff: "",
    visualStaff: "",
    time: "2026-02-21",
    bvid: "BV1q9fjB4EfN",
    notes: "",
    timestampStart: 0,
    timestampEnd: 0,
    videoPath: "BV1q9fjB4EfN.mp4",
  },
]